@startuml
actor guest
actor user
actor admin

user --> (просмотреть товары)
user --> (добавить в корзину товары)
user --> (заказать товары)
user --> (написать в техподдержку)

guest --> (просмотреть товары)
guest --> (добавить в корзину товары)

admin ->(добавить/изменить/удалить товары на сайте)
admin --> (просмотреть товары)

@enduml
